apiVersion: v1
kind: Service
metadata:
  name: np-svc
  namespace: ns1
spec:
  ports:
  - nodePort: 32203
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: np-test
  type: NodePort
status:
  loadBalancer: {}
