apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-nginx
spec:
  podSelector:
    matchLabels:
      app: nginx
  ingress:
  - from:
    - podSelector:
        matchLabels:
          run: pod-2
    ports:
      - protocol: TCP
        port: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-nginx
  namespace: default
spec:
  podSelector:
    matchLabels:
     run: pod-2
  policyTypes:
    - Ingress
  ingress:
    - from:
       - podSelector:
          matchLabels: 
           run: pod-3
      ports:
        - protocol: TCP
          port: 8080
          
